questapp/urls.py
from django.urls import path
from . import views

app_name = 'questapp'
urlpatterns = [path('', views.IndexView.as_view(), name='index'),
               path('<int:pk>/', views.DetailView.as_view(), name='detail'),
               path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
               path('<int:question_id>/vote/', views.vote, name='vote'),
               ]

questator/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('questapp.urls')),
    path('admin/', admin.site.urls),
]

questapp/models.py
import datetime
import time

from django.db import models
from django.utils import timezone


# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date_published')

    def __str__(self):
        return self.question_text

    def recently_published(self):
        now = timezone.now()
        return now >= self.pub_date >= now - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

questapp/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.utils import timezone

from .models import Question, Choice
from django.urls import reverse
from django.views import generic


# Create your views here.
class IndexView(generic.ListView):
    template_name = 'questapp/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).exclude(choice=None).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'questapp/detail.html'

    def get_queryset(self):
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        )


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'questapp/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        context = {'question': question, 'error_message': "You didn't select a choice."}
        result = render(request=request, template_name='questapp/detail.html', context=context)
    else:
        selected_choice.votes += 1
        selected_choice.save()
        result = HttpResponseRedirect(reverse('questapp:results', args=(question_id,)))
    return result

questapp/templates/questapp/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'questapp:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>
<a href="{% url 'questapp:index' %}">Change order?</a>

questapp/templates/questapp/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'questapp:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

questapp/templates/questapp/results.html
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
    <li>
        {{ choice.choice_text }} -- {{ choice.votes }} vote {{ choice.votes|pluralize }}
    </li>
    {% endfor %}
</ul>

<a href="{% url 'questapp:detail' question.id %}">Trink again?</a><br>
<a href="{% url 'questapp:index' %}">Change order?</a>